### ISSUE TITLE
Please add me :)

### ISSUE THREAD

**Issue by craig** [denog/chatterliste#102]
Name: Stefan Behte

Nick: _Craig_

NIC-Handle (optional): SB11275-RIPE

ASN (optional): 198913

Organisation (optional): Babiel GmbH  

Organisation URL (optional): https://www.babiel.com

**Comment by tvberlin** [comment]
@craig please create a MR, thank you.

**Comment by craig** [comment]
FYI: https://github.com/denog/chatterliste/issues/new/choose from DENOG channel topic leads directly to here, and it even mentions:
"
Don't feel like editing JSON? Open a Issue here and answer the questions."

Thank you for the explanation, it might be helpful to change the text. Of course my PR failed at first... :D

**Comment by RichiH** [comment]
Good point.

https://github.com/denog/chatterliste/pull/104
https://github.com/denog/chatterliste/pull/105
