### ISSUE TITLE
add person

### ISSUE THREAD

**Issue by fzinkelink11** [denog/chatterliste#127]
Name: Florian Zinke

Nick: 

NIC-Handle (optional):

ASN (optional): 34309

Organisation (optional):  Link11

Organisation URL (optional): www.link11.com

**Comment by tvberlin** [comment]
Hi Florian, would you mind raising a pull request w/ your data?
If you're not comfortable with working with Git, we'll do it for you, of course.

**Comment by RichiH** [comment]
Cross-ref: https://github.com/denog/chatterliste/pull/131
