### ISSUE TITLE
Morris Görke

### ISSUE THREAD

**Issue by mgoerke76** [denog/chatterliste#149]
Name: Morris Goerke
Nick: mgoerke

NIC-Handle (optional, if changed): [MG26595-RIPE](https://apps.db.ripe.net/db-web-ui/lookup?source=ripe&key=MG26595-RIPE&type=person)

ASN (optional, if changed): [AS208571](https://apps.db.ripe.net/db-web-ui/myresources/detail/aut-num/AS208571/false)

Organisation (optional, if changed): iternas GmbH

Organisation URL(optional, if changed): [iternas GmbH](https://www.iternas.com)

**Comment by tmklfss** [comment]
Done https://github.com/denog/chatterliste/commit/2d9d8e1d3df0ab2b7e4c43e5bb2ab19ea1640f1f
