### ISSUE TITLE
Thomas King

### ISSUE THREAD

**Issue by tking** [denog/chatterliste#68]
Name: Thomas King

Nick: T-K-S

NIC-Handle (optional):

ASN (optional): 31451

Organisation (optional): Works for DE-CIX

Organisation URL (optional): www.de-cix.net

**Comment by RichiH** [comment]
Willst du uns das als PR schicken oder sollen wir den fuer dich bauen? :)

**Comment by tking** [comment]
Das mache ich gerne selber!

**Comment by tvberlin** [comment]
Danke @tking, dann machen wir das hier zu.
