### ISSUE TITLE
change qoreQyaS

### ISSUE THREAD

**Issue by qoreQyaS** [denog/chatterliste#99]
Name: Sven Grewe
Nick: qoreQyaS

NIC-Handle (optional, if changed):

ASN (optional, if changed): 35258

Organisation (optional, if changed): akquinet AG

Organisation URL(optional, if changed): https://akquinet.com/

**Comment by tvberlin** [comment]
Dear @qoreQyaS, would you mind raising a pull request?
Thanks!

**Comment by tvberlin** [comment]
Thanks, merged.
